In [47]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [48]:
np.array([2, 3, 4, 5], dtype = 'int64')

array([2, 3, 4, 5], dtype=int64)

In [49]:
np.array([range(i, i + 3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
np.array(range(1, 3))

array([1, 2])

In [51]:
np.array([range(i, i + 3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [52]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [56]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.random.random((3, 3))

array([[0.77834548, 0.94957105, 0.66252687],
       [0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438]])

In [59]:
np.random.normal(0, 1, (3, 3))

array([[-0.07318342, -0.66572066, -0.04411241],
       [-0.36326702, -0.01234481,  0.04212149],
       [ 1.95929589, -0.1984257 ,  0.33053441]])

In [60]:
np.random.randint(0, 10, (3, 3))

array([[4, 1, 2],
       [9, 1, 4],
       [6, 8, 2]])

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.empty(3)

array([1., 1., 1.])

배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 
이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 
초기화를 하지 않는 empty 명령을 사용할 수 있다. 
empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 
있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.

In [63]:
np.random.seed(0)

컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다. 
어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 
보이는 수열을 생성한다. 이런 시작 숫자를 시드(seed)라고 한다. 일단 생성된 난수는 
다음번 난수 생성을 위한 시드값이 된다. 따라서 시드값은 한 번만 정해주면 된다. 
시드는 보통 현재 시각등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있다. 
특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있다.

In [64]:
x1 = np.random.randint(10, size = 6)
x1

array([5, 0, 3, 3, 7, 9])

In [65]:
x2 = np.random.randint(10, size = (3, 4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [66]:
x3 = np.random.randint(10, size = (3, 4, 5))
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [67]:
x1.ndim

1

In [68]:
x3.shape

(3, 4, 5)

In [69]:
x2.size

12

In [70]:
x2.dtype

dtype('int32')

In [71]:
x2.itemsize

4

In [72]:
x2.nbytes

48

In [73]:
x1[1]

0

In [74]:
x1[-2]

7

In [75]:
x2[1, 2]

8

In [76]:
x2[1, 2] = 134

In [77]:
x2

array([[  3,   5,   2,   4],
       [  7,   6, 134,   8],
       [  1,   6,   7,   7]])

In [78]:
x4 = np.arange(10)
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x4[0:5]

array([0, 1, 2, 3, 4])

In [80]:
x4[5:]

array([5, 6, 7, 8, 9])

In [81]:
x4[4:7]

array([4, 5, 6])

In [82]:
x4[::2]

array([0, 2, 4, 6, 8])

In [83]:
x4[1::2]

array([1, 3, 5, 7, 9])

In [84]:
x4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [85]:
x4[5::-2]

array([5, 3, 1])

In [86]:
x5 = np.random.randint(10, size = (3, 4))
x5

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [87]:
x5[:2, :3]

array([[4, 3, 4],
       [8, 4, 3]])

In [88]:
x5[:, ::2]

array([[4, 4],
       [8, 3],
       [5, 0]])

In [89]:
x5[::-1, ::-1]

array([[1, 0, 5, 5],
       [7, 3, 4, 8],
       [4, 4, 3, 4]])

In [90]:
x5[0]

array([4, 3, 4, 4])

In [91]:
x5[0, :]

array([4, 3, 4, 4])

In [92]:
x5[:, 0]

array([4, 8, 5])

In [93]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


In [98]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [100]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [101]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [102]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [103]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
y = np.array([3, 4, 6])
y

array([3, 4, 6])

In [109]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 6])

In [110]:
z = np.array([2, 3, 4])
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 6, 2, 3, 4])

In [112]:
x2 = np.random.randint(1, 10, (3, 3))
x2

array([[3, 1, 8],
       [6, 1, 3],
       [8, 3, 3]])

In [113]:
x3 = np.random.randint(1, 10, (3, 3))
x3

array([[4, 4, 3],
       [4, 5, 2],
       [3, 2, 5]])

In [114]:
np.concatenate([x2, x3])

array([[3, 1, 8],
       [6, 1, 3],
       [8, 3, 3],
       [4, 4, 3],
       [4, 5, 2],
       [3, 2, 5]])

In [115]:
np.concatenate([x2, x3], axis = 1)

array([[3, 1, 8, 4, 4, 3],
       [6, 1, 3, 4, 5, 2],
       [8, 3, 3, 3, 2, 5]])

In [117]:
x1 = np.array([1, 2, 3])

In [118]:
np.vstack([x1, x2])

array([[1, 2, 3],
       [3, 1, 8],
       [6, 1, 3],
       [8, 3, 3]])

In [119]:
np.vstack([x2, x1])

array([[3, 1, 8],
       [6, 1, 3],
       [8, 3, 3],
       [1, 2, 3]])

In [121]:
np.hstack([x2, x3])

array([[3, 1, 8, 4, 4, 3],
       [6, 1, 3, 4, 5, 2],
       [8, 3, 3, 3, 2, 5]])

In [139]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = list(np.array(x))
y

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [140]:
x1, x2, x3 = np.split(y, [3, 6])
print(x1, x2, x3)

[1 2 3] [4 5 6] [ 7  8  9 10]


In [141]:
t = np.arange(0, 16).reshape(4, 4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [148]:
upper, lower = np.vsplit(t, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [146]:
left, right = np.hsplit(t, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [152]:
q = np.array(t).reshape(2, 2, 4)
q

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [153]:
np.dsplit(q, 2)

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [154]:
x = np.array([1, 2, 3])
x + 5

array([6, 7, 8])

In [155]:
x - 4

array([-3, -2, -1])

In [156]:
x * 3

array([3, 6, 9])

In [157]:
x / 2

array([0.5, 1. , 1.5])

In [158]:
x ** 2

array([1, 4, 9], dtype=int32)

In [159]:
x // 3

array([0, 0, 1], dtype=int32)

In [160]:
x % 3

array([1, 2, 0], dtype=int32)

In [163]:
np.add(x, 2)

array([3, 4, 5])

In [164]:
np.abs(x)

array([1, 2, 3])

In [165]:
print(x)

[1 2 3]


In [171]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [172]:
y= np.zeros(10)
np.power(2, x, out = y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [173]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [174]:
np.multiply.reduce(x)

120

In [175]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [177]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [180]:
L = np.random.random(100)
sum(L)

51.621916957498335

In [181]:
np.sum(L)

51.62191695749832

In [182]:
np.max(L)

0.9850322788832359

In [183]:
L.max()

0.9850322788832359

In [184]:
np.min(L)

5.535686500857118e-05

In [185]:
L.min()

5.535686500857118e-05

In [186]:
r = np.random.random((3, 4))
r

array([[0.92621293, 0.32531031, 0.95287067, 0.0139484 ],
       [0.53346568, 0.30458203, 0.88286   , 0.25062272],
       [0.67741183, 0.81042409, 0.43214805, 0.75213452]])

In [189]:
r.sum()

6.861991225964667

In [190]:
r.min(axis = 1)

array([0.0139484 , 0.25062272, 0.43214805])