In [3]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

print('Size :', x.size())
print('Shape :', x.shape)
print('랭크(차원) :', x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size : torch.Size([3, 3])
Shape : torch.Size([3, 3])
랭크(차원) : 2


In [4]:
x = torch.unsqueeze(x, 0)
print(x)

print(f'Size : {x.size()}')
print(f'Shape : {x.shape}')
print(f'랭크(차원) : {x.ndimension()}')

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size : torch.Size([1, 3, 3])
Shape : torch.Size([1, 3, 3])
랭크(차원) : 3


In [5]:
x = x.view(9)
print(x)

print(f'Size : {x.size()}')
print(f'Shape : {x.shape}')
print(f'랭크(차원) : {x.ndimension()}')

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size : torch.Size([9])
Shape : torch.Size([9])
랭크(차원) : 1


In [6]:
try:
    x = x.view(2, 4)
except Exception as e:
    print(e)

shape '[2, 4]' is invalid for input of size 9


In [7]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print(f"w size : {w.size()}")
print(f"x size : {x.size()}")
print(f'w : {w}')
print(f'x : {x}')

w size : torch.Size([5, 3])
x size : torch.Size([3, 2])
w : tensor([[-0.3401,  2.3923, -0.0405],
        [-0.6320,  0.6591, -0.3554],
        [-0.4817, -0.0613, -0.2975],
        [ 0.3138,  0.4709, -1.0337],
        [ 1.6857,  1.5290, -0.4772]])
x : tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
b = torch.randn(5, 2, dtype=torch.float)
print(f'b : ')