100 Numpy Exercise
===

100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.16.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4.  How to find the memory size of any array (★☆☆)

In [4]:
arr.itemsize

8

### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
arr = np.arange(0, 9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
arr = np.nonzero([1,2,0,0,4,0])
arr

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
arr = np.random.random((3,3,3))
arr

array([[[0.55675642, 0.92922018, 0.54855961],
        [0.21030893, 0.39757382, 0.82067191],
        [0.23521986, 0.06999207, 0.87609151]],

       [[0.60853552, 0.64495956, 0.7200293 ],
        [0.76132921, 0.52935157, 0.24009485],
        [0.86676094, 0.97883044, 0.94517358]],

       [[0.34932948, 0.39465262, 0.54900591],
        [0.72177535, 0.41543505, 0.95381682],
        [0.06063757, 0.14159598, 0.78216641]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr = np.random.rand(10,10)
max_num = arr.max()
min_num = arr.min()
print(max_num, min_num)

0.9888962339341322 0.010035858886703886


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
arr = np.random.random(30)
arr.mean()

0.5977047497091148

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
arr = np.diag(1+np.arange(4), k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
arr = np.zeros((8,8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [28]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [29]:
arr = np.random.random((5,5))
arr = (arr - np.mean(arr)) / np.std(arr)
arr

array([[-1.28606183,  0.58306587, -0.39643728, -1.45985072,  0.67410268],
       [-0.14328185, -1.04515656,  0.10820315,  1.85654741,  0.86120798],
       [ 1.34077575,  0.41701799, -0.05590167,  0.81404959, -0.50112791],
       [ 0.04010004, -1.17435563,  1.34272104, -1.32839325,  0.25644135],
       [-1.69063757,  0.14504294,  1.85305006, -0.58024877, -0.63087281]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [30]:
color = np.dtype([('r', np.ubyte, 1),
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
arr1 = np.ones((5,3))
arr2 = np.zeros((3,2))
arr1.dot(arr2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\default.DESKTOP-S5Q9GAA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\default.DESKTOP-S5Q9GAA\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### 29. How to round away from zero a float array ? (★☆☆)

In [42]:
arr = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[10.  3.  1.  1. -6. -7. -1.  1. -4.  5.]


### 30. How to find common values between two arrays? (★☆☆)

In [43]:
arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 10)
np.intersect1d(arr1, arr2)

array([0, 2, 3, 5, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np

defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [5]:
today = np.datetime64('today', 'D') 
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [6]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [7]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [8]:
arr = np.random.uniform(0, 10, 10)

print(arr - arr % 1)
print(np.floor(arr)) # 음의 방향으로 가장 가까운 정수 반환
print(np.ceil(arr)-1)  # 양의 방향으로 가장 가까운 정수 반환
print(arr.astype(int))
print(np.trunc(arr))  # 양의 방향으로 가까운 정수 반환

[6. 6. 6. 1. 7. 0. 1. 3. 9. 5.]
[6. 6. 6. 1. 7. 0. 1. 3. 9. 5.]
[6. 6. 6. 1. 7. 0. 1. 3. 9. 5.]
[6 6 6 1 7 0 1 3 9 5]
[6. 6. 6. 1. 7. 0. 1. 3. 9. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
arr = np.arange(0, 5)
arr1 = np.ones((5,1))
arr * arr1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [12]:
def generator():
    for x in range(10):
        yield x
arr = np.fromiter(generator(), dtype=float, count=-1)  # Create a new 1-dimensional array from an iterable object.
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [13]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [15]:
arr = np.random.random(10)
arr.sort()
arr

array([0.05270265, 0.12207987, 0.14953114, 0.15960218, 0.18566849,
       0.39363174, 0.4429437 , 0.53557   , 0.6170148 , 0.89047508])

### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
import numpy as np
arr = np.arange(0, 10000)

%time
arr.sum()

%time 
# reduce dimension by 1
np.add.reduce(arr)

Wall time: 0 ns
Wall time: 0 ns


49995000

### 42. Consider two random array A and B, check if they are equal (★★☆)

In [16]:
A = np.random.randn(0,10,10)
B = np.random.randn(0,10,10)

# checking values and shape
print(np.array_equal(A, B))

# checking only shape
print(np.allclose(A, B))

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [18]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [19]:
arr = np.random.random((10, 2))
x, y = arr[:, 0], arr[:, 1]
r = np.sqrt(x**2, y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.820345   0.00718835 0.04613718 0.53872676 0.81932685 0.55452982
 0.4869495  0.70355094 0.94910291 0.48962533]
[0.75486186 1.56180393 1.50252777 0.57134168 0.235944   1.00421131
 0.14012455 0.66815914 0.12487782 0.84508977]


### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [20]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.06052533 0.2673153  0.58047601 0.         0.80644987 0.41261003
 0.63445685 0.23912958 0.74463674 0.19463598]


### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

###  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [21]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. How to print all the values of an array? (★★☆)

In [23]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

52


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [2]:
import numpy as np

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [3]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.65071494 0.36379666 0.36685752 0.2476956  0.34850919
  0.41347664 0.27458864 0.65784665 0.68304816]
 [0.65071494 0.         0.45898129 0.3466754  0.73239152 0.43378219
  0.26748442 0.37935754 0.84668413 0.73083301]
 [0.36379666 0.45898129 0.         0.40172195 0.58010497 0.03496975
  0.20379145 0.28119407 0.9119453  0.87501758]
 [0.36685752 0.3466754  0.40172195 0.         0.38869117 0.36687351
  0.2526805  0.13082265 0.55262637 0.48374135]
 [0.2476956  0.73239152 0.58010497 0.38869117 0.         0.55660148
  0.55857054 0.37777719 0.4303572  0.49347701]
 [0.34850919 0.43378219 0.03496975 0.36687351 0.55660148 0.
  0.1734599  0.24728384 0.8803127  0.84116559]
 [0.41347664 0.26748442 0.20379145 0.2526805  0.55857054 0.1734599
  0.         0.18304468 0.80290494 0.7349998 ]
 [0.27458864 0.37935754 0.28119407 0.13082265 0.37777719 0.24728384
  0.18304468 0.         0.63888935 0.59388584]
 [0.65784665 0.84668413 0.9119453  0.55262637 0.4303572  0.8803127
  0.80290494 0.6388893

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [4]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [5]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [7]:
arr = np.arange(9).reshape(3,3)
for i, a in np.ndenumerate(arr):
    print(i, a)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [8]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [12]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [14]:
arr = np.random.rand(5,10)
arr1 = arr - arr.mean(axis=1, keepdims=True)
arr1

array([[ 0.25356655, -0.516022  , -0.01200212,  0.45411766,  0.28204825,
         0.00978655, -0.25121135,  0.45185754, -0.2499009 , -0.42224018],
       [-0.38728114, -0.58288545,  0.21565869, -0.05664795,  0.22758298,
         0.07203692,  0.27920811, -0.01199215,  0.29877744, -0.05445745],
       [-0.32852355,  0.30648053, -0.26844423,  0.21583702,  0.12740884,
        -0.17210481,  0.0462805 ,  0.02124495, -0.02146896,  0.07328969],
       [ 0.21648032,  0.25194856, -0.40589681, -0.02537237, -0.0666479 ,
        -0.33557097,  0.2146596 ,  0.25478912, -0.18532118,  0.08093163],
       [-0.43239315,  0.4002063 , -0.07106803,  0.4363428 , -0.36368996,
        -0.31881494, -0.31638143,  0.31703814,  0.32806685,  0.02069342]])

#### 59. How to sort an array by the nth column? (★★☆)

In [15]:
arr = np.random.randint(0,10,(3,3))
arr[arr[:, 1].argsort()]

array([[3, 1, 4],
       [7, 4, 0],
       [3, 8, 5]])

### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [8]:
import numpy as np

arr = np.random.uniform(0,1,10)

# given value z
z = 0.5

# flat : vector로 변환
# argmin : 최솟값의 index를 반환
m = arr.flat[np.abs(arr-z).argmin()] 
print(arr)
print(m)

[0.73017702 0.10274265 0.53453621 0.07145861 0.12162203 0.81866036
 0.03846965 0.78786036 0.39868579 0.13454779]
0.5345362058583907


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [9]:
arr1 = np.arange(3).reshape(1,3)
arr2 = np.arange(3).reshape(3,1)
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 63. Create an array class that has a name attribute (★★☆)

In [10]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None : return
        self.info = getattr(obj, 'name', 'no name')
        
arr = NamedArray(np.arange(10), 'range_10')
print(arr.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [11]:
arr = np.ones(10)
arr2 = np.random.randint(0, len(arr), 20)
np.add.at(arr, arr2, 1)
print(arr)

[4. 2. 4. 2. 3. 3. 3. 3. 4. 2.]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [12]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X) # count number of occurences of each value inarray of non-negative ints
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [13]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [17]:
arr = np.random.randint(0, 10, (3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)

[[68 64 55 39]
 [49 57 65 49]
 [42 58 26 56]]


### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [19]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(D)
print(S)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.91330097 0.73322342 0.57270066 0.9951887  0.95191758 0.07316977
 0.32786518 0.9129991  0.46657175 0.82623021 0.73055746 0.36362929
 0.12530724 0.08011721 0.66708125 0.56036523 0.00137528 0.88746559
 0.45639462 0.93246538 0.05120594 0.87466546 0.44534129 0.64430091
 0.58570067 0.51194642 0.01991523 0.38721138 0.48549068 0.80947744
 0.64174543 0.48581372 0.97810595 0.78456529 0.10255463 0.4490539
 0.03383328 0.74808061 0.24186127 0.37070116 0.33249973 0.88105158
 0.48717978 0.49026248 0.71385292 0.0400608  0.25982201 0.12714565
 0.06064572 0.2891791  0.61141165 0.73916044 0.90955462 0.08763428
 0.89916919 0.35472258 0.58971389 0.79205563 0.13222069 0.03248989
 0.06334757 0.42524898 0.21804748 0.1821447  0.84159915 0.57691274
 0.29302954 0.51013288 0.15355237 0.37111339 0.32148195 0.46111451
 0.17607208 0.24998633 0.44906596 0.09973129 0.64826554 0.26676443
 0.830908   0.53338845 0.74221606 0.49050794 0.04294207 0.96005397
 0.19128214 0.01881225 0.4653768  0.0455768  0.96733652 0.14464

#### 69. How to get the diagonal of a dot product? (★★★)

In [20]:
arr1 = np.random.uniform(0,1,(5,5))
arr2 = np.random.uniform(0,1,(5,5))

np.sum(arr1 * arr2.T, axis=1)

array([1.00036997, 0.38306824, 2.08051866, 0.97403709, 1.50638316])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [34]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [4]:
import numpy as np

arr1 = np.ones((5,5,3))
arr2 = 2 * np.ones((5,5))
arr1 * arr2[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [5]:
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [6]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 62) ( 1, 86) ( 4, 14) ( 4, 92) ( 6, 32) ( 6, 49) (13, 29) (13, 81)
 (14, 92) (21, 22) (21, 82) (22, 82) (24, 32) (24, 59) (29, 81) (32, 49)
 (32, 59) (32, 72) (32, 94) (54, 65) (54, 76) (61, 86) (61, 96) (62, 86)
 (65, 76) (72, 94) (75, 75) (75, 81) (86, 96)]


### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [7]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### 75. How to compute averages using a sliding window over an array? (★★★)

In [14]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

arr = np.arange(20)
print(moving_average(arr, n = 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [16]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [17]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1])

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [18]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.91229104 13.73594765  3.32868157  1.10783378  4.75946896 10.68499569
  0.63724543  8.45415221  3.1105097   2.31957174]


### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [2]:
import numpy as np
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Compute a matrix rank (★★★)

In [3]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [4]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [5]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 4]
   [3 0 2]
   [1 1 1]]

  [[0 4 0]
   [0 2 3]
   [1 1 0]]

  [[4 0 4]
   [2 3 3]
   [1 0 1]]

  [[0 4 2]
   [3 3 3]
   [0 1 0]]

  [[4 2 2]
   [3 3 2]
   [1 0 2]]

  [[2 2 4]
   [3 2 1]
   [0 2 4]]

  [[2 4 3]
   [2 1 2]
   [2 4 0]]

  [[4 3 0]
   [1 2 4]
   [4 0 2]]]


 [[[3 0 2]
   [1 1 1]
   [3 4 3]]

  [[0 2 3]
   [1 1 0]
   [4 3 3]]

  [[2 3 3]
   [1 0 1]
   [3 3 0]]

  [[3 3 3]
   [0 1 0]
   [3 0 4]]

  [[3 3 2]
   [1 0 2]
   [0 4 1]]

  [[3 2 1]
   [0 2 4]
   [4 1 4]]

  [[2 1 2]
   [2 4 0]
   [1 4 3]]

  [[1 2 4]
   [4 0 2]
   [4 3 0]]]


 [[[1 1 1]
   [3 4 3]
   [2 3 3]]

  [[1 1 0]
   [4 3 3]
   [3 3 0]]

  [[1 0 1]
   [3 3 0]
   [3 0 2]]

  [[0 1 0]
   [3 0 4]
   [0 2 1]]

  [[1 0 2]
   [0 4 1]
   [2 1 2]]

  [[0 2 4]
   [4 1 4]
   [1 2 2]]

  [[2 4 0]
   [1 4 3]
   [2 2 2]]

  [[4 0 2]
   [4 3 0]
   [2 2 0]]]


 [[[3 4 3]
   [2 3 3]
   [4 0 1]]

  [[4 3 3]
   [3 3 0]
   [0 1 2]]

  [[3 3 0]
   [3 0 2]
   [1 2 2]]

  [[3 0 4]
   [0 2 1]
   [2 2 1]]

  [[0 4 1]
   

### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [6]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 12 13  2 18]
 [12  7  8  6  4]
 [13  8  3 42 11]
 [ 2  6 42  8  6]
 [18  4 11  6  6]]


### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [7]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [8]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)

### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

#### 89. How to get the n largest values of an array (★★★)

In [9]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [10]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [2]:
import numpy as np

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [3]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.21 s ± 42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
371 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
333 ms ± 23.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [4]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 5 6 7]


### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [5]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 3 3]
 [0 1 3]
 [3 2 0]
 [0 4 2]
 [4 3 3]
 [2 2 3]
 [2 2 1]
 [1 3 4]
 [3 0 0]
 [0 4 1]]
[[2 3 3]
 [0 1 3]
 [3 2 0]
 [0 4 2]
 [4 3 3]
 [2 2 3]
 [2 2 1]
 [1 3 4]
 [3 0 0]
 [0 4 1]]
[[2 3 3]
 [0 1 3]
 [3 2 0]
 [0 4 2]
 [4 3 3]
 [2 2 3]
 [2 2 1]
 [1 3 4]
 [3 0 0]
 [0 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [6]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [7]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 3]
 [0 4 1]
 [0 4 2]
 [1 3 4]
 [2 2 1]
 [2 2 3]
 [2 3 3]
 [3 0 0]
 [3 2 0]
 [4 3 3]]


### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [8]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.15977866, 0.26787995, 0.25575869, 0.02848172, 0.24182222,
        0.15155164, 0.03842437, 0.42092931, 0.31145602, 0.32379455],
       [0.02703535, 0.04532663, 0.04327565, 0.00481925, 0.04091753,
        0.0256433 , 0.0065016 , 0.07122334, 0.05269992, 0.05478766],
       [0.04705945, 0.07889842, 0.07532835, 0.00838869, 0.07122366,
        0.04463635, 0.01131709, 0.12397589, 0.09173283, 0.09536689],
       [0.32444091, 0.54394758, 0.51933457, 0.05783398, 0.49103566,
        0.30773541, 0.07802318, 0.8547242 , 0.6324316 , 0.65748578],
       [0.32410307, 0.54338116, 0.51879378, 0.05777376, 0.49052434,
        0.30741496, 0.07794193, 0.85383417, 0.63177304, 0.65680113],
       [0.36440299, 0.61094677, 0.58330212, 0.06495752, 0.55151758,
        0.34563984, 0.08763346, 0.96000242, 0.71032956, 0.73846972],
       [0.17652055, 0.29594888, 0.28255754, 0.03146609, 0.26716078,
        0.16743149, 0.04245055, 0.46503502, 0.34409093, 0.35772231],
       [0.05695028, 0.09548108, 0.0911606

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [9]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [10]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [11]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.18912367  0.19287781]
